### Create Account
POST http://localhost:4000/api/auth
Content-Type: application/json

{
  "name": "victor",
  "email": "correo@correo.com",
  "password": "password",
  "password_confirmation":"password",
  "confirmed":true
}

###Confirm Account
POST http://localhost:4000/api/auth/confirm-account
Content-Type: application/json

{
  "token": "536815"
  
}

###Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email":"correo2@correo.com",
  "password":"password"
  
}

# Para separar una peticon de otra cada una debe tener ### 3 sino no aparece el send Request porque no sabe que son distintos bloques.