### Create Account
POST http://localhost:4000/api/auth
Content-Type: application/json

{
  "name": "victor",
  "email": "correo@correo.com",
  "password": "password",
  "password_confirmation":"password",
  "confirmed":true
}

###Confirm Account
POST http://localhost:4000/api/auth/confirm-account
Content-Type: application/json

{
  "token": "113299"
  
}

# Para separar una peticon de otra cada una debe tener ### 3 